info:
  app:
    name: HCG
    description: Master microservices kapsamında öğreniyorum.
    version: 1.0.0

server:
  port: 8085
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  security:
    user:
      name: hcguler
      password: Ab123456
  messages:
    basename: messages
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/hcg
    username: HCG
    password: hcg12345
    driverClassName: org.postgresql.Driver
    initialization-mode: always

logging:
  level:
    com:
      hcg: DEBUG


classproperties:
  maximum: 20
  minimum: 1
  description: "TEST AÇIKLAMA"
